### ISSUE TITLE
Doesn't do on the fly linting plus keeps throwing error on file save.

### ISSUE THREAD

**Issue by nim23** [AtomLinter/linter-scss-lint#101]
Versions:
Atom - 1.1.0
Ruby -  2.2.3p173
scss-lint - 0.42.2
linter-scss-lint - 2.4.0

Linter doesn't seem to be doing on the fly linting, plus I keep seeing the below error on file save:
![screen shot 2015-11-02 at 3 48 28 pm](https://cloud.githubusercontent.com/assets/1999331/10886359/9f63d248-8179-11e5-8c75-0796bf44abc7.png)

Any help would be appreciated thanks!!

**Comment by Arcanemagus** [comment]
Does `scss_lint` work from the command line for you? That stack trace is coming from `scss_lint` itself.

**Comment by nim23** [comment]
Nope I am getting the same result from the command line itself as well.

**Comment by Arcanemagus** [comment]
I would file an issue over [there](https://github.com/brigade/scss-lint) then to attempt to get this figured out. I'm marking this as closed as it isn't an issue with `linter-scss-lint`.
