### ISSUE TITLE
Repeated configuration error

### ISSUE THREAD

**Issue by abea** [AtomLinter/linter-scss-lint#105]
```
TypeError: Invalid configuration: private method 'load' called for Psych:Module
  at /Users/[username]/.atom/packages/linter-scss-lint/lib/init.coffee:56:23
```

I'm getting this error on any Sass file updating now. The only think I can think of is that something in my Homebrew update changed. the Atom emmet and pigment packages also updated today, if that might matter.

**Comment by SpainTrain** [comment]
Ya, line 56 is where scss-lint is executed and this looks like a Ruby error.  can you run `scss-lint` on the CLI?

**Comment by abea** [comment]
Same error. It does look like the scss_lint gem issue. We can close this. Thanks.
