### ISSUE TITLE
Indentation Errors

### ISSUE THREAD

**Issue by benbrownlol** [AtomLinter/linter-scss-lint#111]
I'm not sure if this is the correct place for this and I'm not sure if its even your plugin thats causing it but I keep getting a lint error telling me to use 2 indentation spaces instead of 4 but personally I think 4 is more readable. 

Is there a way to change this or ignore this error from lint-scss? or is it a atom-linter issue?

**Comment by Arcanemagus** [comment]
Most linters at this point have their name specified and so should show (unless disabled in the `linter` package settings), but this one looks like it hasn't been updated so if you aren't seeing which linter it is probably this one. Does `scss_lint` from the command line show the same messages?

It looks like the [default scss_lint config](https://github.com/brigade/scss-lint/blob/v0.43.2/config/default.yml#L89) has indentation set to 2 spaces so it's likely that you just need to create a configuration file that changes the default.

**Comment by SpainTrain** [comment]
https://github.com/AtomLinter/linter-scss-lint/issues/84

**Comment by SpainTrain** [comment]
You can create a config file to customize to your needs - https://github.com/brigade/scss-lint#configuration

For example, in your project directory you can create `.scss-lint.yml`:

```yml
linters:
  Indentation:
    character: tab
    width: 3
````

or just turn it off:

```yml
linters:
  Indentation:
    enabled: false
```

**Comment by benbrownlol** [comment]
Excellent thank you guys!!
