### ISSUE TITLE
TypeError: Invalid configuration: private method `load' called for Psych:Module

### ISSUE THREAD

**Issue by David-Polehonski** [AtomLinter/linter-scss-lint#128]
```
TypeError: Invalid configuration: private method `load' called for Psych:Module
    at file:///C:/Users/My-User/.atom/packages/linter-scss-lint/lib/init.coffee:59:23
    at process._tickCallback (node.js:368:9)
```

Receive this error on everytime I update a SCSS file, windows 10, Atom current release (1.5.3)

**Comment by Arcanemagus** [comment]
Looks like this was the old catch all when it couldn't parse the output. This is now handled much more intelligently so I'm marking this as closed.
