### ISSUE TITLE
Error: sh: mysql: line 1

### ISSUE THREAD

**Issue by akmur** [AtomLinter/linter-scss-lint#129]
Hello, I get the weirdest issue:

This is my error message:

Error: sh: mysql: line 1: syntax error: unexpected end of file sh: error importing function definition for mysql' sh: mysqladmin: line 1: syntax error: unexpected end of file sh: error importing function definition formysqladmin'

and more in detail

```text
Error: sh: mysql: line 1: syntax error: unexpected end of file
sh: error importing function definition for `mysql'
sh: mysqladmin: line 1: syntax error: unexpected end of file
sh: error importing function definition for `mysqladmin'
    at parameters.exit (/Users/alessandromuraro/.atom/packages/**linter-scss-lint**/node_modules/atom-linter/lib/helpers.js:47:27)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Any idea what might be the cause?

![image](https://cloud.githubusercontent.com/assets/957841/13490560/bb9b4770-e12d-11e5-8668-ac901fb99b37.png)

**Comment by akmur** [comment]
I think the issue might be with partially downloaded updates, or something like that. Will be reinstalling from scratch and come back if the issue persists.

**Comment by akmur** [comment]
Sorry to be back, the problem persists for me... any idea anyone?

**Comment by Arcanemagus** [comment]
Looks to be another configuration issue with a shell, @steelbrain?

**Comment by steelbrain** [comment]
@akmur Can you tell us which shell you're using?

**Comment by akmur** [comment]
Hello, I just found out that the issue was caused by these lines in bashrc, which I added ages ago. Removing those lines fixed the issue.

# Export MAMP MySQL executables as functions
# Makes them usable from within shell scripts (unlike an alias)
mysql() {
    /Applications/MAMP/Library/bin/mysql "$@"
}
mysqladmin() {
    /Applications/MAMP/Library/bin/mysqladmin "$@"
}
export -f mysql
export -f mysqladmin

**Comment by steelbrain** [comment]
I am glad you found the issue
