### ISSUE TITLE
Error when opening scss files

### ISSUE THREAD

**Issue by markandrewj** [AtomLinter/linter-scss-lint#130]
Hello,

I really love atom linter. I am trying it out with scss, but I am currently getting an error. I followed the instructions, I am not sure if it is a bug or I made a mistake. Any help would be great.

I have the gem dependancy installed.
![screen shot 2016-03-05 at 10 58 06 pm](https://cloud.githubusercontent.com/assets/142597/13552561/d422429a-e325-11e5-9ff3-18914be72659.png)

I am using rvm, so I created the wrapper then added it to the executable path.
![screen shot 2016-03-05 at 10 34 44 pm](https://cloud.githubusercontent.com/assets/142597/13552495/62aaea7e-e323-11e5-8253-8e1ed6542127.png)

But when I open a scss file I get this error.
![screen shot 2016-03-05 at 10 35 58 pm](https://cloud.githubusercontent.com/assets/142597/13552507/8a25ff94-e323-11e5-9f3b-f933c94c21fa.png)

I don't think it is the issue, but this is the scss-lint.yml I currently have in the directory with my .scss file.
![screen shot 2016-03-05 at 10 48 15 pm](https://cloud.githubusercontent.com/assets/142597/13552535/7bd1226a-e324-11e5-8f66-25b5634c3590.png)

**Comment by Arcanemagus** [comment]
Does `scss-lint` from the command line work when you try to run it on a file? The error you posted _seems_ to be an internal error in it, it's certainly not something from this plugin.

**Comment by markandrewj** [comment]
Hey, thanks for the quick reply. After looking a bit more into this, it looks like the problem is the Ruby gem, not the plugin. I well play with it a bit more, and if I can't figure out what the problem is, post a ticket for the gem. I have quite a few gems at the moment that are working fine, so I think it is a bug.

**Comment by ocarreterom** [comment]
`rvm rubygems latest --force` in the project directory works for me.

**Comment by markandrewj** [comment]
Sorry for the late reply, I well give this a try. I have been using vim more then atom over the last bit. Thanks for the feedback.
