### ISSUE TITLE
Error when opening a .scss file

### ISSUE THREAD

**Issue by fili2306** [AtomLinter/linter-scss-lint#140]
When I open a `.scss` file i get this error:

![atom error scss](https://cloud.githubusercontent.com/assets/12660678/14586128/994450fc-048e-11e6-9cd2-7e742b1cf85f.PNG)

**Comment by vnabet** [comment]
Same error.

![capture](https://cloud.githubusercontent.com/assets/1830490/14598623/78814a4e-0553-11e6-9e5a-12c273334b6e.JPG)

**Comment by datatypevoid** [comment]
Same here. 

![39c88b15835958aebaebb3d4ad21063d](https://cloud.githubusercontent.com/assets/10481547/14704448/b56dc064-0782-11e6-9df7-9a7e5f88f045.png)

**Comment by Arcanemagus** [comment]
Are any of you on Windows?

**Comment by datatypevoid** [comment]
`Windows 10 x64`, I should have mentioned in my last comment.

**Comment by Arcanemagus** [comment]
If you are on Windows there was a bug in a sub-dependency that broke execution, you can force an update of that sub-dependency by:

1. Closing Atom
2. Deleting/moving _all_ `linter-____` packages from your `.atom/packages` folder
3. Running `apm install linter-name` for each of the packages you removed in the previous step

That should force all the installed versions of the `atom-linter` dependency to be updated to the latest, which in turn should mean that the latest `sb-exec` is installed.

**Comment by datatypevoid** [comment]
I'll give it a shot right now and update this comment with the results.

**Comment by vnabet** [comment]
@Arcanemagus Win 7. Your trick works fine. Thanks !

**Comment by Arcanemagus** [comment]
@fili2306 Are you still having issues?

**Comment by fili2306** [comment]
@Arcanemagus I've followed those things and everything seems to be working fine, thanks!
And sorry for the delayed response.

**Comment by Arcanemagus** [comment]
Awesome, glad to hear it! Marking this as closed. If you have further problems please open a new issue.
