### ISSUE TITLE
Use node npm scss-lint or sass-lint instead of scss-lint gem

### ISSUE THREAD

**Issue by anaibol** [AtomLinter/linter-scss-lint#147]

**Comment by Arcanemagus** [comment]
The `sass-lint` on `npm` is already implemented as https://github.com/AtomLinter/linter-sass-lint, and it handles both SCSS and SASS.

I'm not sure what you mean by `scss-lint` on `npm` as there is no such package, and [scsslint](https://www.npmjs.com/package/scsslint) is just a wrapper around the Ruby `scss-lint` (just like this already is).

Regardless of what you meant, it would require rewriting the entire linter, and would break functionality for users expecting to integrate with the Ruby `scss-lint`.

**Comment by anaibol** [comment]
Hi! Sorry I didn't know about linter-sass-lint linting scss files.
Thanks!
