### ISSUE TITLE
change indentation

### ISSUE THREAD

**Issue by Lionardo** [AtomLinter/linter-scss-lint#15]
Is there a way to change the indentation to 4 spaces? If so, where can i do that?

**Comment by tomodwyer** [comment]
You need to setup a `.scss-lint.yml` file in the directory you are linting

For example, if you wanted to set indentation warnings to 4 spaces, you could set up your `.scss-lint.yml` file with the following code:
````yaml
linters:
  Indentation:
    width: 4
`````

For more info see: [https://github.com/brigade/scss-lint#configuration](https://github.com/brigade/scss-lint#configuration)

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58
