### ISSUE TITLE
C:\Ruby22-x64\bin\ruby.exe: No such file or directory

### ISSUE THREAD

**Issue by adi518** [AtomLinter/linter-scss-lint#155]
Happens since yesterday's update. The executable is where it should be.

**Comment by jamieconnolly** [comment]
Do you remember what version you updated from by any chance? Was the rest of the 3.0.x series working fine for you?

**Comment by adi518** [comment]
Everything was sweet until latest version.

**Comment by Arcanemagus** [comment]
@jamieconnolly There is possibly an issue with `atom-linter@5` on Windows, haven't had time to diagnose it yet myself but AppVeyor builds are failing for several projects on it :disappointed:.

**Comment by jamieconnolly** [comment]
Thanks @Arcanemagus, that goes along with my initial thought too. Was just about to push through a release to revert `atom-linter` back to `^4.6.1`

**Comment by jamieconnolly** [comment]
@adi518 — I've just released `v3.0.3`. Can you update and see if this issue still exists?

**Comment by adi518** [comment]
I'll let you know in a jiffy.

**Comment by adi518** [comment]
That fixed it!

**Comment by jamieconnolly** [comment]
Glad to hear it!
