### ISSUE TITLE
Invalid response error

### ISSUE THREAD

**Issue by PCateNumbersUSA** [AtomLinter/linter-scss-lint#159]
For the past couple of versions I've had to disable the plugin because any changes to scss files with it on give the following error:

`SCSS-Lint returned an invalid response, check your console for more info.`

![screen shot 2016-05-11 at 10 06 08 am](https://cloud.githubusercontent.com/assets/3307733/15183661/0673beae-1760-11e6-910b-89ba1a33b170.png)

When I look at the console I get the following error:
```
[Linter-SCSS-Lint] SyntaxError: Unexpected token u(…) undefined local variable or method `file' for #<SCSSLint::Engine:0x007fd19c232df8>
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/engine.rb:50:in `build_from_file'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/engine.rb:21:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/runner.rb:29:in `new'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/runner.rb:29:in `find_lints'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/runner.rb:19:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/runner.rb:18:in `each'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/runner.rb:18:in `run'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/cli.rb:65:in `scan_for_lints'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/cli.rb:50:in `act_on_options'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/lib/scss_lint/cli.rb:27:in `run'
/Library/Ruby/Gems/2.0.0/gems/scss_lint-0.43.0/bin/scss-lint:6:in `<top (required)>'
/usr/local/bin/scss-lint:23:in `load'
/usr/local/bin/scss-lint:23:in `<main>'
```

**Comment by jamieconnolly** [comment]
Which version of SCSS-Lint are you using? It should be displayed at the bottom of the console output.

**Comment by PCateNumbersUSA** [comment]
SCSS-Lint: 0.43.0
Linter-SCSS-Lint: 3.0.3
Atom: 1.7.3
Ruby: 2.0
OSX: 10.11.4

**Comment by jamieconnolly** [comment]
Can you bump SCSS-Lint to `0.43.2` (or to the latest version) and see if you're still experiencing this error?  Thanks!

**Comment by PCateNumbersUSA** [comment]
That fixed it. I updated to the 0.48, and now no errors.

**Comment by artkondrashov** [comment]
Help solve the problem
<img width="1279" alt="2018-12-04 23 30 09" src="https://user-images.githubusercontent.com/36848023/49470988-bb4da200-f81c-11e8-99e5-77cc523f7f8f.png">
