### ISSUE TITLE
Failed to spawn command scss-lint

### ISSUE THREAD

**Issue by leofle** [AtomLinter/linter-scss-lint#16]
Failed to spawn command scss-lint. Make sure scss-lint is installed and on your PATH
![screen shot 2015-01-25 at 12 14 04 pm](https://cloud.githubusercontent.com/assets/2674606/5891133/cb005708-a48b-11e4-8c21-0df722e10a4b.jpg)

this just appear on load.

atom version: 0.175.0

**Comment by hd-deman** [comment]
did you configure `scssLintExecutablePath` in package configuration?

**Comment by jacklam718** [comment]
Also I'm got same error, but I solved, I just closed the Atom then run these commands:
gem install scss-lint and apm install linter-scss-lint, finally open Atom again.

So you can have a try, my environment is Mac OS X, Atom version 0.190.0

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58
