### ISSUE TITLE
Old version off scss-lint error message

### ISSUE THREAD

**Issue by KrisCoulson** [AtomLinter/linter-scss-lint#160]
I believe  reverting to the previous version in this [commit](https://github.com/AtomLinter/linter-scss-lint/commit/5df6278e52a8a0387776d72c763a9cc2131c7986) has caused errors with outdated resources.

![image](https://cloud.githubusercontent.com/assets/6943688/15188320/f53df1fa-1759-11e6-9952-2f7abcb699ef.png)

**Comment by jamieconnolly** [comment]
As of `v3.0.0`, we require `v0.43.2` or higher of `scss-lint` so this error message is valid. You'll need to upgrade your version for the plugin to work 👍

**Comment by davidpmccormick** [comment]
The readme at https://atom.io/packages/linter-scss-lint still tells you to `gem install scss-lint` rather than `scss_lint` – this had me stumped for ages. I'd submit a PR, but can't see where that text is generated.

**Comment by francisrupert** [comment]
Worked for me only **after**...

```
gem uninstall scss-lint
gem uninstall scss_lint 
gem install scss_lint 
```

**Comment by KrisCoulson** [comment]
Ahh @davidpmccormick and @francisrupert  thank you that helped! I clicked through to the link to scss-lint and just installed the gem from the github. But the linkter requires scss_lint. The readme points to two different gems to use.

**Comment by jamieconnolly** [comment]
Thanks for noticing that @davidpmccormick. I've pushed a release that fixes that text.

@francisrupert — I'll add a section about upgrading from `scss-lint` into the `README`.

**Comment by jamieconnolly** [comment]
@KrisCoulson — the `scss_lint` gem is actually just an up-to-date version of the `scss-lint` gem. It was a mistake that slipped through causing it to reference the older gem. Sorry for any inconvenience!
