### ISSUE TITLE
using old version scss-lint

### ISSUE THREAD

**Issue by mPanasiewicz** [AtomLinter/linter-scss-lint#164]
As in title, my atom says that I'm using too old version. I use the newest version of atom 1.8 and the linter-scss-lint 3.0.4. Anyone has got the same problem?

**Comment by mPanasiewicz** [comment]
OK, I solved the problem. Reinstalled the scss-lint gem,
$ gem uninstall scss-lint
Remove executables:
        scss-lint

in addition to the gem? [Yn]  y
Removing scss-lint
Successfully uninstalled scss-lint-0.38.0


$ gem install scss_lint
Successfully installed scss_lint-0.48.0
Parsing documentation for scss_lint-0.48.0
Installing ri documentation for scss_lint-0.48.0
Done installing documentation for scss_lint after 2 seconds
1 gem installed

**Comment by BenSpace48** [comment]
Thanks. This worked for me also, it's confusing because there is `scss-lint` and `scss_lint`.
