### ISSUE TITLE
Often repeats lint notices and double-counts warnings/errors

### ISSUE THREAD

**Issue by fburleigh** [AtomLinter/linter-scss-lint#17]
Facts: Atom .176, linter 0.10.1, linter-scss-lint 0.0.11, OS X, scss-lint gem 0.33, ruby 2.2.

* Open an SCSS file
* Introduce a simple flaw like "no space between colon and value:" `height:33px;`
* Save and close file
* Reopen file
* Put cursor on the line with the flaw

If your experience is like mine, scss-linter will show its warning twice (one above the other), and will first show the correct warning count, and a moment later will double that count.

**Comment by adamshiervani** [comment]
I have the same issue

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58
