### ISSUE TITLE
Autofix issues

### ISSUE THREAD

**Issue by pedzed** [AtomLinter/linter-scss-lint#174]
I have a list of colors which need to be lowercase. I can of course just quickly make it lowercase with JavaScript, but it would be nice if it could be done by a click of a button.

What is required to have this feature?

**Comment by Arcanemagus** [comment]
This would need to be implemented in [`scss-lint`](https://github.com/brigade/scss-lint) first, before it could be done here.

Ideally it would be in the style of `eslint`, where fixes are _proposed_ in the error message result itself. Most linters though only implement an option on the CLI to automatically apply any fixes known, which could work here but isn't as finely grained as the first option.

**Comment by Arcanemagus** [comment]
In that particular case you mention, inside Atom you can just highlight the text and do <kbd>Ctrl</kbd>+<kbd>k</kbd> then <kbd>l</kbd> (while still holding <kbd>Ctrl</kbd>).
