### ISSUE TITLE
Not respecting scssLintExcludedLinters

### ISSUE THREAD

**Issue by sevenfoxes** [AtomLinter/linter-scss-lint#18]
I've configured a few ignored linters, they work fine in sublime but they don't work in atom. Am I doing it right or is this a bug?

```cson
"linter-scss-lint":
  scssLintExecutablePath: "~/scss-lint"
  scssLintExcludedLinters: [
    "PropertySortOrder"
    "Comment"
    "SpaceBeforeBrace"
    "EmptyLineBetweenBlocks"
    "NameFormat"
  ]
```

**Comment by hd-deman** [comment]
this feature was released in `0.0.14`  
change `scssLintExecutablePath` to `executablePath`
and `scssLintExcludedLinters` to `excludedLinters` and try again.
