### ISSUE TITLE
additional arguments - how to add?

### ISSUE THREAD

**Issue by PixelT** [AtomLinter/linter-scss-lint#199]
How to add additional arguments?
I have .scss-lint.yml file on dropbox (not in project path)
In package setting, in Additional Arguments field I write:
```
--config=${home}/Dropbox/_linters/.scss-lint.yml
```
or
```
--config=~/Dropbox/_linters/.scss-lint.yml
```
but I always give an error at console:
```
init.coffee [sm]:83 [Linter-SCSS-Lint] SyntaxError: Unexpected token N in JSON at position 0(…) No such file or directory - ${home}/Dropbox/_linters/.scss-lint.yml
```

It's possible to add config from "external" source?

**Comment by Arcanemagus** [comment]
You need to specify the full path (`/home/username/Dropbox/...`), expansion of `~` or `${home}` is magic your shell does for you, not real paths 😛.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
