### ISSUE TITLE
Indentation Spacing Warning

### ISSUE THREAD

**Issue by diversionarytactic** [AtomLinter/linter-scss-lint#200]
I know this is "bad" according to the docs, but I'm on a project where it's required we use a 4 space indentation. I've searched and tried to change the config in Atom and various other methods to no avail.

How might I be able to change the 2 space setting to 4 or at a minimum turn off the warnings as there are tons of them.

**Comment by Arcanemagus** [comment]
This project is just a wrapper around `scss-lint`, you'll need to [configure it](https://github.com/brigade/scss-lint#configuration) to your liking, it looks like the relevant setting would be [`Indentation`](https://github.com/brigade/scss-lint/blob/3e05ec43f8d44362789a29119fe95c8af51bea06/config/default.yml#L92).
