### ISSUE TITLE
Look for .scss-lint.yml in atom root directory

### ISSUE THREAD

**Issue by ManifoldDigital** [AtomLinter/linter-scss-lint#204]
I keep my plugins and atom settings synced across my work rig and my home system, I also have several projects going on at the same time. In order for me to keep things backed up I can have files in the root atom directory (the same directory with atom's config file) and those will be backed up. It would be great if I could have the scss-lint file in that directory. This will also let me override the default configurations for all my projects/future projects without having to create an individual file and maintain that specific file when I want global sweeping changes.

**Comment by Arcanemagus** [comment]
Closing as `wontfix`. Your configuration should live with your project. If you _need_ a global file across all your project place it in a parent directory of all the projects. The config file search searches all parent directories till it finds the file it is looking for or hits the filesystem root.
