### ISSUE TITLE
[BUG] Gives warning on cubic-bezier in snake case setting

### ISSUE THREAD

**Issue by LAUVz** [AtomLinter/linter-scss-lint#205]
Gives warning on cubic-bezier in snake case setting
even tho correct syntax is used.

![untitledss](https://cloud.githubusercontent.com/assets/8288020/24046216/171a4960-0b22-11e7-8568-372f9f9104bb.png)

**Comment by Arcanemagus** [comment]
You should file this over on [`scss-lint`](https://github.com/brigade/scss-lint), this project is merely a wrapper around that allowing its results to be displayed in Atom.
