### ISSUE TITLE
Failed to spawn command css-lint (this is back?)

### ISSUE THREAD

**Issue by gabrielalack** [AtomLinter/linter-scss-lint#209]
Saw some closed issues from 2015 about this which were closed as fixed.

I just tried installing this package from the settings panel. Got the error below.

Uninstalled

Installed again via APM

Same error on Atom 1.16.0

```
Error: Failed to spawn command scss-lint. Make sure scss-lint is installed and on your PATH
Error: Failed to spawn command `scss-lint`. Make sure `scss-lint` is installed and on your PATH
    at /Users/Gabriel/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.js:102:24
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Arcanemagus** [comment]
Do you have [SCSS-Lint](https://github.com/brigade/scss-lint) installed? Also please read the giant notice posted on their repo 😉.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
