### ISSUE TITLE
Add config option to only lint when a config file is found in the project

### ISSUE THREAD

**Issue by raphinesse** [AtomLinter/linter-scss-lint#21]
This is great to have when one has to work with legacy projects.

For reference, [linter-jscs](https://github.com/AtomLinter/linter-jscs) has this:
![2015-04-06 19_02_04-settings - c__users_raphinesse_desktop - atom](https://cloud.githubusercontent.com/assets/1006620/7008060/7764a5ea-dc8f-11e4-85fb-3991c331dbf3.png)

**Comment by steelbrain** [comment]
We'are actually discouraging that kind-of linter enable/disable and are working on an alternative solution, see atom-community/linter#744
