### ISSUE TITLE
Question: How do you disable the propertySortOrder?

### ISSUE THREAD

**Issue by collinpage** [AtomLinter/linter-scss-lint#212]
Hi,

Title says it all!

I've tried to add this code to the .scss-lint.yml located in .atom/packages/linter-scss-lint/spec/fixtures but I still get the warnings.

![image](https://user-images.githubusercontent.com/12260627/29322837-f6ab3606-81ac-11e7-97af-87bbda95023b.png)

Thanks for the help!

**Comment by Arcanemagus** [comment]
That file is only used to test whether this package properly reads your project's configuration file. You would want to create your own `.scss-lint.yml` file in your project root with that directive in order for this to work.

Also please note that scss-lint (which this is a wrapper around) is in maintenance only mode as Sass has moved away from Ruby which `scss-lint` depends on. You should look into moving to [stylelint](https://stylelint.io/) or [sass-lint](https://github.com/sasstools/sass-lint), both of which have Linter providers 😉.
