### ISSUE TITLE
Global configuration path for .scss-lint.yml

### ISSUE THREAD

**Issue by muuvmuuv** [AtomLinter/linter-scss-lint#214]
Short but simple: A global configuration path would be great. 

I store all my config files in my mac documents folder and want to store a global .scss-lint.yml also there. So I don't have to copy and paste the same yml in every project

> Keep muuving

**Comment by Arcanemagus** [comment]
It will search for a file named after the "Config Name" setting's value (default: `.scss-lint.yml`) starting at the current file's directory and moving up until it finds it or it hits the file system root.

This means you could place a `.scss-lint.yml` file in some parent directory of all your projects and it would work. Not that I recommend this as your project's configuration should live with your project, but it would _work_.
