### ISSUE TITLE
Invalid Linter received after 3.2.0

### ISSUE THREAD

**Issue by danielocdh** [AtomLinter/linter-scss-lint#226]
> [Linter] Invalid Linter received
> These issues were encountered while registering a Linter named 'scss-lint'
>   • Linter.lintsOnChange must be a boolean

I'm using atom 1.33.1 x64 under windows, it reports there isn't more updates.
I'm using linter 2.3.0, it reports there isn't more updates.

I tried removing my atom completely, reinstalled with 1.34.0 and got the exact same issue.

**Comment by dzirtusss** [comment]
+++ same here
