### ISSUE TITLE
Failed to spawn command `scss-lint`

### ISSUE THREAD

**Issue by BenLeggiero** [AtomLinter/linter-scss-lint#241]
```
[Linter] Error running scss-lint Error: Failed to spawn command `scss-lint`. Make sure `scss-lint` is installed and on your PATH
    at /Users/BenLeggiero/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.js:130:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(anonymous) @ /Users/BenLeggiero/.atom/packages/linter/lib/linter-registry.js:155
_tickCallback @ internal/process/next_tick.js:188
```

linter-scss-lint 3.2.1
Atom 1.35.1 x64
macOS 10.14.4

**Comment by Arcanemagus** [comment]
> Make sure `scss-lint` is installed and on your PATH

As the error message says, you need to have installed [scss-lint](https://github.com/brigade/scss-lint) in order for this package to work. Please note that scss-lint is no longer maintained, you should look into something like [linter-stylelint](https://atom.io/packages/linter-stylelint) instead.
