### ISSUE TITLE
use nodesass

### ISSUE THREAD

**Issue by techdragon** [AtomLinter/linter-scss-lint#3]
Can we get either a fork or option or some way to use nodesass instead of rubysass... It feels very unecessary to install rubysass just for scss linting in Atom when I'm not using it for any of my sass projects at all, everything is nodesass.

**Comment by blakebutcher** [comment]
It has been a while. Has node sass stabilised to a point where it could now be used?

**Comment by iam4x** [comment]
This is not related to the package. Related to `scss-lint` https://github.com/brigade/scss-lint/issues/397
