### ISSUE TITLE
The linter binary 'scss-lint' cannot be found.

### ISSUE THREAD

**Issue by bobrocke** [AtomLinter/linter-scss-lint#34]
My `config.cson` file has

```
"linter-scss-lint":
  scssLintExecutablePath: "/Users/bob/.rvm/gems/ruby-2.0.0-p247@rails3/bin/scss-lint"
```
and that file is there.

**Comment by hd-deman** [comment]
change `scssLintExecutablePath` to `executablePath`.
see https://github.com/AtomLinter/linter-scss-lint/releases/tag/v1.0.0

**Comment by bobrocke** [comment]
That didn't help. Now I have:
```
"linter-scss-lint":
  ExecutablePath: "/Users/bob/.rvm/gems/ruby-2.0.0-p247@rails3/bin/scss-lint"
```
and still get the error.

**Comment by jptaranto** [comment]
Same error for me. `scss-lint` runs fine from the command line.

```json
  "linter-scss-lint":
    executablePath: "/Users/jack/.rvm/gems/ruby-2.2.1/bin/scss-lint"
```

**Comment by dsmy** [comment]
Having the same issue myself. Paths are setup correctly and it runs fine from the command line.

**Comment by artoale** [comment]
:+1: me too

**Comment by ArekSredzki** [comment]
Same ![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by dylan** [comment]
yup. :+1:

**Comment by phildionne** [comment]
Same, and using rbenv. Path is: `"/Users/pdionne/.rbenv/shims/scss-lint`

**Comment by alienlebarge** [comment]
I'm using *rbenv* too.
I've set the executable Path to `/Users/memyselfandi/.rbenv/versions/2.2.2/bin/scss-lint` in the settings and it solved the problem.

hope it will help...
