### ISSUE TITLE
1.0.2 no longer honors scss-lint.yml file in home directory

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-scss-lint#38]
I've had this config file for a while, and after installing 1.0.2, all the items I had set to ignore are flagged.

Linter config file:  http://cl.ly/code/44233k252e3I/scss-lint.yml

**Comment by hd-deman** [comment]
fixed in 1.0.3 check it please

**Comment by smlombardi** [comment]
fixed.  thanks.
