### ISSUE TITLE
The linter binary 'scss-lint' cannot be found.

### ISSUE THREAD

**Issue by bobrocke** [AtomLinter/linter-scss-lint#39]
Really. I have the file and the path to it is correct, but I continue to get The linter binary 'scss-lint' cannot be found errors:

![bin](https://cloud.githubusercontent.com/assets/2962426/7760270/bf38de74-ffe7-11e4-9a5c-4470ff0cec5b.jpg)

**Comment by mjesuele** [comment]
I'm having the same issue. Absolutely sure that I'm putting in the right executable path.

**Comment by brianO3world** [comment]
I was having the same issue. Did you try getting the path with 'which scss-lint'?

**Comment by egardner** [comment]
I'm experiencing this as well – I use RBENV, not RVM, but the behavior is otherwise the same.
This was working without any issues for weeks, but stopped working in the last few days.

**Comment by drawcard** [comment]
Same problem here... just ran ```sudo gem install scss-lint``` on a MBP 15" 2015 model, Yosemite 10.10.3

**Comment by drawcard** [comment]
Actually - could this be the problem?

```bash
WARNING: `scss-lint` has been renamed to `scss_lint` to follow proper RubyGems naming conventions. Update your Gemfile or relevant install scripts to install `scss_lint`.
```

**Comment by PJL101** [comment]
I'm using rbenv, and it was working a few days ago until today. Happy to provide any logs/info if needed.

**Comment by FalkoJoseph** [comment]
I have the exact same problem. Using Rbenv as well. :disappointed:

**Comment by DominicBarnard** [comment]
Same problem here: using rbenv installed with homebrew on osx.

I managed to get this working by adding this line:
`@executablePath = atom.config.get 'linter-scss-lint.executablePath'`
to the `updateOption` function in `linter-scss-lint.coffee` in the package.
Then used `$ which scss-lint` at command line which gave me `/usr/local/var/rbenv/shims/scss-lint` and I entered that as the executable path setting.

I've not done any atom package dev before so there may be a better way but I can PR if you like.

**Comment by bobrocke** [comment]
@DominicBarnard Where, exactly in `linter-scss-lint.coffee`?
```
  updateOption: (option) =>
    super(option)

    # build cmd
    @cmd = 'scss-lint --format=XML'
    @cmd += " --exclude-linter=#{@excludedLinters.toString()}" if @excludedLinters and @excludedLinters.length > 0

    config = findFile @cwd, ['.scss-lint.yml']
    if config
      @cmd += " -c #{config}"
```

**Comment by DominicBarnard** [comment]
I have it here:
```coffee
updateOption: (option) =>
    super(option)

    @executablePath = atom.config.get 'linter-scss-lint.executablePath'

    # build cmd
    @cmd = 'scss-lint --format=XML'
    @cmd += " --exclude-linter=#{@excludedLinters.toString()}" if @excludedLinters and @excludedLinters.length > 0

    config = findFile @cwd, ['.scss-lint.yml']
    if config
      @cmd += " -c #{config}"
```
I've never done any atom dev or even coffeescript before so there may be a better way but this got it working for me :)

**Comment by bobrocke** [comment]
Works!

On my system (Mac OS X 10.10.3), I put this in `config.cson`:
```
"linter-scss-lint":
    executablePath: "/usr/local/bin/scss-lint"
```

@DominicBarnard Thanks!

**Comment by DominicBarnard** [comment]
@bobrocke awesome, glad you got it working!

**Comment by dsandstrom** [comment]
@DominicBarnard That doesn't seem like the fix.  The Linter package should be handling the setting of the variable: https://github.com/AtomLinter/Linter/blob/d22fb154ae4698a932fffd09649ed4268d25e3f9/lib/linter.coffee#L76.

**Comment by dsandstrom** [comment]
The fix for me is #42.  Until it gets merged, you will have to download @caseywebdev 's fork (https://github.com/caseywebdev/linter-scss-lint/tree/json) and apm link it in.

**Comment by jptaranto** [comment]
```json
  "linter-scss-lint":
    executablePath: "/Users/jack/.rvm/gems/ruby-2.2.1/bin/scss-lint"
```

scss linter only works if I start atom from the command line, otherwise I get the scss-lint cannot be found message.

**Comment by adidahiya** [comment]
I tried setting the `executablePath` in `config.cson` but that didn't help. I'm on scss-lint v0.38.

Starting atom from the command line was the only thing that fixed this for me.

**Comment by tbremer** [comment]
I took @DominicBarnard example simplified it to just setting the option, which worked perfectly for me.

```coffee
updateOption: (option) =>
    super(option)

    @executablePath = atom.config.get 'linter-scss-lint.executablePath'
```

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58

**Comment by gouroujo** [comment]
I still got the same problem with atomLinter / rbenv installed with Homebrew.
As suggested in https://github.com/willcosgrove/atom-ruby-bundler I've added the line 
```
process.env.PATH = "#{process.env.HOME}/.rbenv/shims:#{process.env.HOME}/.rbenv/bin:#{process.env.PATH}"
```
that solved the issue

**Comment by SpainTrain** [comment]
@gouroujo that is great!  Any chance you have a couple min to open a PR to the README file with instructions for rbenv that may help others with the same issue?
