### ISSUE TITLE
excludedLinters not excluding?

### ISSUE THREAD

**Issue by cbleslie** [AtomLinter/linter-scss-lint#48]
I'm going mad. 
This is the linter portion of my ```config.cson``` file.

```CSON
  "linter-scss-lint":
    excludedLinters: [
      "PropertySortOrder"
    ]
```
Am I doing something wrong?
I am currently running ```Atom 1.0```.
The expected outcome is that atom lint won't give me the errors that would normally berate me for having the props out of order, but the warnings still appear.

**Comment by dsandstrom** [comment]
I'm not sure why `excludedLinters` is not working, I haven't tried it.  However, you could add a *.scss-lint.yml* file in you home directory

```yml
linters:
  PropertySortOrder:
    enabled: false
```

**Comment by iam4x** [comment]
@cbleslie It should be put in normal config file from linter like @dsandstrom said :)
