### ISSUE TITLE
Unknown error at line 1 col 1, cmdline works.

### ISSUE THREAD

**Issue by cjwelborn** [AtomLinter/linter-scss-lint#49]
I'm getting `Unknown Error at line 1 col 1` on all scss files. This is after setting the correct executable path, where before it would just complain that it couldn't find it. I'm using `scss-lint v. 0.40.1` and `linter-scss-lint v. 1.0.5`. I can't see any errors in the dev console. It says `active linter-scss-lint` though. The other linter plugins are working fine. If I run `scss-lint` on the command line it works fine.

**Comment by cjwelborn** [comment]
Update: For some reason if I start atom with `atom --dev --wait` `linter-scss-lint` works fine.

**Comment by iam4x** [comment]
What is `--wait` doing ?

**Comment by cjwelborn** [comment]
I don't think `--wait` isn't helping the problem. I was just being clear about what I ran. I was trying it to keep `atom` in the foreground in my console, hoping an error message would be printed to stdout. I still have to `Ctrl + C` to get my prompt back. 

Anyway, plain old `atom --dev` lets `linter-scss-lint` work just fine.

**Comment by HelloTiago** [comment]
I just installed the latest version of `scss-lint` and I'm getting the same issue. Every SCSS file has this error.

**Comment by ruanmer** [comment]
same here

**Comment by Kamilius** [comment]
And exactly same for me.

**Comment by dustindowell22** [comment]
I'm having the same problem as well. I'm curious, are all of you guys also using RVM? I had a similar problem using scss-lint with a Brackets extension, but I recently made the switch to Atom, thinking it might be different.

**Comment by Kamilius** [comment]
@dustindowell22 as for me - yes. I am using RVM

**Comment by cjwelborn** [comment]
No RVM for me.

**Comment by ewohlken** [comment]
+1

**Comment by bastiRe** [comment]
Same probem here, also using RVM

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58
