### ISSUE TITLE
"Unknown Error at line 1 col 1" and auto-open executable path file

### ISSUE THREAD

**Issue by distriker** [AtomLinter/linter-scss-lint#50]
Hi everyone,
perhaps ask it looks a bit stupid, but I need an answer because I have tryed and tryed and the linter don't lint. As there isn't a **which** command on Windows 8 to make what you say on the settings file (make **which scss-lint**), I found on StackOverflow an interesting answer to "[an alternative to which on Windows](http://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line)": **where** command.

So I tryed different ways with it to find the executable path, but nothing appeared. So I think that the executable should be on the Atom package folder. I went to that folder (C:/Users/$userName/.atom/packages/linter-scss-lint/lib), where there are an init.coffee and linter-scss-lint.coffee. I have tryed with each one, but with each one occurs the same error. Then, the issue dettected is only at the line 1 col 1, like in the title of this issue. The error shown is: **Unknown Error at line 1 col 1**

I have installed the main linter and the php linter works fine. What it could be happen with it?

Regards, *Iván*

**Comment by dustindowell22** [comment]
@distriker I think you're supposed to be linking to the executable path of the ruby gem scss_lint not the linter.

But, I'm having the same issue on OS X with this as my executable path.

```
/Users/foobar/.rvm/gems/ruby-2.2.1/bin/scss-lint
/Users/foobar/.rvm/gems/ruby-2.2.1/bin/
```

**Comment by bobrocke** [comment]
I can confirm `atom --dev` "fixes" the problem.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58
