### ISSUE TITLE
Hide warnings and only display error messages

### ISSUE THREAD

**Issue by drawcard** [AtomLinter/linter-scss-lint#51]
Hi,

I was wondering if it's possible to hide warnings and only display errors, as some SCSS files I have give off plenty of warnings but it's mainly stylistic stuff that I'm not too concerned about. I posted on the linter project originally but was directed here for more info.

https://github.com/AtomLinter/Linter/issues/692

**Comment by iam4x** [comment]
Hi I've answered on the original issue to open a discussion on how we could implement this.

**Comment by iam4x** [comment]
Fixed with: https://github.com/AtomLinter/Linter/pull/698
