### ISSUE TITLE
scss linting produces error "Unable to parse SCSS file: Invalid US-ASCII character "\xe2"

### ISSUE THREAD

**Issue by StudioSpindle** [AtomLinter/linter-scss-lint#55]
the error "Unable to parse SCSS file: Invalid US-ASCII character "\xe2" at line 1 col 1 is in multiple files no matter what character you put there.

It occurs in multiple files, even though @charset "UTF-8"; have declared at the first line of my 'master' scss file

OS X: Yosemite (v10.10.4)

![schermafbeelding 2015-07-13 om 08 26 37](https://cloud.githubusercontent.com/assets/9882035/8652221/cf041be2-297d-11e5-875f-38c1a860f209.png)

**Comment by StudioSpindle** [comment]
Perhaps setting the application environment would do the trick, but not sure how that should be done just yet. See for info http://code.dblock.org/2011/06/09/compass-invalid-us-ascii-character-xe2.html

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58

**Comment by steelbrain** [comment]
Reopening based on slack discussion

**Comment by StudioSpindle** [comment]
@steelbrain Found the issue. There was a similarity in all the files which produced this error. They all used a ascii character like for instance `˃` or `↑`. 

So would this be a linter issue?
- Can't parse ASCII characters
- Doesn't know which line the character is on

If this issue doesn't relate to the scss linting please feel free to close this issue.

**Comment by steelbrain** [comment]
I think that's more like a `scss-lint` issue than `linter-scss-lint` issue.

**Comment by StudioSpindle** [comment]
I agree.

**Comment by jkmaxwell** [comment]
@xonecas just solved this here by making me update from 0.42.2 to 0.42.3

**Comment by ronilaukkarinen** [comment]
I still have this problem. Here's the line in question:

![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screen%20Shot%202016-04-07%20at%2010.11.05.png "Screenshot.")

Can this be fixed?

**Comment by Arcanemagus** [comment]
@ronilaukkarinen That error is coming from `scss-lint`, you will need to either update your version that you are using, or if the latest version is still showing this then file an issue on their repo.

**Comment by ronilaukkarinen** [comment]
Oh, I had 0.38 installed, just ran gem update. My bad... thanks! fixed in latest version.
