### ISSUE TITLE
`lintOnFly` does not work in 2.0.0

### ISSUE THREAD

**Issue by caseywebdev** [AtomLinter/linter-scss-lint#61]
I've published a package with working `lintOnFly` called `linter-scss-lint-caseywebdev`

The updated code can be seen at https://github.com/caseywebdev/linter-scss-lint

**Comment by tbremer** [comment]
+1 It'd be great to have linting on the fly again. Until there, great work @caseywebdev!

**Comment by steelbrain** [comment]
@caseywebdev I discussed it further with @park9140 and he has convinced me that it's okay to write to a temp file for the linters that don't support writing to stdin, we'll be adding a method in the helper module `atom-linter` for that, and PRs are welcome always.

**Comment by caseywebdev** [comment]
Sounds good, thanks

**Comment by bobrocke** [comment]
Is this working now? It doesn't seem to be, for me.

**Comment by steelbrain** [comment]
@caseywebdev I've added a `tempFile` method to helper module btw.
