### ISSUE TITLE
updating to v2.0.0 caused my executable path to dissapear

### ISSUE THREAD

**Issue by StudioSpindle** [AtomLinter/linter-scss-lint#63]
It worked fine but stopped working after updating to v2.0.0. Manual input was needed.

Solution: run '$ which scss-lint' in terminal to find out where the executable was. Copy this rule.

Then open the settings of the package 'linter scss lint' to find the executable path text input field and manually add the previously copied rule. Is it possible to automate this process or at least keep the old value?

**Comment by steelbrain** [comment]
I think we might have renamed the config key

**Comment by willdady** [comment]
+1 

Package is now broken for me. Setting the path to scss-lint via the settings screen or manually via my config.cson file has no effect.

I have this in my config.cson file which I've confirmed is the correct path: `scssLintExecutablePath: "/usr/bin/scss-lint"`

**Comment by steelbrain** [comment]
To anyone facing this issue, the old key in your settings is actually atom's upgrade issue, to fix rename config to `executablePath`

**Comment by uiureo** [comment]
I had the same issue.

I think it would be nice for most users if the plugin finds executable path automatically.
