### ISSUE TITLE
Invalid output format specified: json

### ISSUE THREAD

**Issue by anthonator** [AtomLinter/linter-scss-lint#65]
I get this when I'm editing Ruby files. Not sure why it's linting Ruby. Reloaded my workspace and Atom is using `language-ruby` for this file.

```
Error: Invalid output format specified: json Run scss-lint --help for usage documentation
Error: Invalid output format specified: json
Run `scss-lint --help` for usage documentation
  at /Users/anthonator/.atom/packages/linter-rubocop/index.coffee:42:27
  at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by anthonator** [comment]
Now that I look more closely at the error it looks like a rubocop problem. Which makes way more sense. Sorry!

**Comment by steelbrain** [comment]
No probs, Glad you were able to find the cause of it.

**Comment by steelbrain** [comment]
No probs, Glad you were able to find the cause of it.
