### ISSUE TITLE
TypeError: Error linting ... No 'scss-lint' executable specified

### ISSUE THREAD

**Issue by anthonydillon** [AtomLinter/linter-scss-lint#66]
I installed and have been using linter-scss-lint for a number of months now and this morning I have started getting this error message when saving any scss file.

```
TypeError: Error linting /home/ant/Documents/Canonical/Git/inspector-animations/static/scss/future.scss: No 'scss-lint' executable specified
  at Object.provider.lint (/home/ant/.atom/packages/linter-scss-lint/lib/init.coffee:41:19)
  at Promise.then._this.emitter.emit.linter (/home/ant/.atom/packages/linter/lib/linter-registry.coffee:57:22)
  at LinterRegistry.triggerLinter (/home/ant/.atom/packages/linter/lib/linter-registry.coffee:56:16)
  at /home/ant/.atom/packages/linter/lib/linter-registry.coffee:50:17
  at Array.map (native)
  at /home/ant/.atom/packages/linter/lib/linter-registry.coffee:48:27
```

**Comment by steelbrain** [comment]
I think the error is quite obvious, You need to provide the `scss-lint` path to the linter.

**Comment by wouterds** [comment]
As @anthonydillon mentioned it used to work for months. I have the same issue, it used to work and all of a sudden it just stopped working and complaining. @steelbrain

**Comment by steelbrain** [comment]
@wouterds what's the result of `which scss-lint`? Also, are you guys on OSX?

**Comment by wouterds** [comment]
```~ » which scss-lint                                                                WouterDS@WouterDS-Macbook-Pro-Retina
/usr/bin/scss-lint```

And yes I'm on OS X. My colleague @filipminev has the same issue (same laptop, same OS X version and a nearly identical Atom configuration).

**Comment by anthonydillon** [comment]
Same which scss-lint output as @wouterds but on 14.04 Ubuntu

**Comment by CristyTarantino** [comment]
+1

**Comment by kevinmartinez** [comment]
OS X here same error. Atom 1.0.9

**Comment by vladiiancu** [comment]
Same issue here. Used to work but now I get this error. All packages up to date. 

But I remember getting some warning regarding chmod for /usr and usr/bin which were like 777 i think and I changed them to 755. Maybe it has something to do with this?

**Comment by wataruoguchi** [comment]
I got the same on OS X v10.11, atom 1.0.19, apm 1.0.5
As @vladiiancu mentioned above I added "executable path" and it got worked.

1. gem install scss_lint
2. apm install linter-scss-lint
3. which scss-lint

Paste the result of '3' into "executable path"

**Comment by jschroeder9000** [comment]
The problem is that there is no default.  The default should be set to `scss-lint` which will use whatever is in my PATH.  I shouldn't have to go set executable path to `scss-lint`.  That makes no sense - it should be the default.

**Comment by JKillian** [comment]
@jschroeder9000 :+1: 
Is there any reason it can't just use `scss-lint`that's on the $PATH by default?

**Comment by SpainTrain** [comment]
> Is there any reason it can't just use scss-lintthat's on the $PATH by default?

There may be a historical reason, but it's totally reasonable that there should be a default that works for a basic ruby install.  I unfortunately do not have bandwidth to attend to this ATM, but will happily review and test a PR.  Created issue https://github.com/AtomLinter/linter-scss-lint/issues/94 for this.
