### ISSUE TITLE
Linter can't find env: ruby_executable_hooks

### ISSUE THREAD

**Issue by Devby** [AtomLinter/linter-scss-lint#68]
OS X 10.11 Beta (15A262e)

```
Error: env: ruby_executable_hooks: No such file or directory
  at exit (/Users/artiomk/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:29:24)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)
```

**Comment by Kamilius** [comment]
Exactly the same issue, even though the proper path from `which scss-lint` result provided into preferences

**Comment by bobrocke** [comment]
I have the error, too, but with OS X 10.10.5.

My `which scss-lint` path is in preferences.

**Comment by GeorgMeyer23** [comment]
+1

**Comment by GeorgMeyer23** [comment]
I resolved it using wrappers for executable path:
$ which scss-lint
`/Users/me/.rvm/gems/ruby-x.x.x/bin/scss-lint`

replace `bin` with `wrappers`, so you get:

`/Users/me/.rvm/gems/ruby-x.x.x/wrappers/scss-lint`

**Comment by bobrocke** [comment]
@GeorgMeyer23 `wrappers`? Why in the world would that weird trick work?!

**Comment by Devby** [comment]
@GeorgMeyer23 it doesn't work for me

**Comment by bobrocke** [comment]
Strangely, it partially worked for me. It will now lint on save, but not on-the-fly.

Mac OS X 10.10.5, Atom 1.0.10.

**Comment by steelbrain** [comment]
@bobrocke `lintOnFly` is unimplemented at the moment because of `scss-lint` limitations, it's being worked on [here](https://github.com/AtomLinter/linter-scss-lint/pull/72)

**Comment by ErikFontanel** [comment]
@GeorgMeyer23 your solution worked for me. I'm on 10.10.14, atom 1.0.11, linter-scss 2.0

**Comment by willpracht** [comment]
I'm still getting this error.

Tried the `wrappers` solution to no avail. It actually breaks harder with this method.

Does it have anything to do with using `rvm` instead of the built-in?

**Comment by SpainTrain** [comment]
How did it break harder, could you provide the error message?

Also, how is your env set up?  e.g, what's the output of 

```
ruby -v
which ruby
which scss-lint
```

**Comment by SpainTrain** [comment]
@Devby are you still experiencing this issue also?

**Comment by Devby** [comment]
"Wrappers" solution works for me now.

**Comment by willpracht** [comment]
@SpainTrain - Sorry about that :).

```bash
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
/Users/willpracht/.rvm/rubies/ruby-2.2.1/bin/ruby
/Users/willpracht/.rvm/gems/ruby-2.2.1/bin/scss-lint
```

The error I get when changing my path to `wrappers`:

> Failed to spawn command `/Users/willpracht/.rvm/gems/ruby-2.2.1/wrappers/scss-lint`. Make sure `/Users/willpracht/.rvm/gems/ruby-2.2.1/wrappers/scss-lint` is installed and on your PATH

Followed by...

> Error: spawn /Users/willpracht/.rvm/gems/ruby-2.2.1/wrappers/scss-lint ENOENT

Seems like it's just that it can't find *scss-lint* via `wrappers`. Which, makes sense.

The other though... not sure what's going on there.

**Comment by SpainTrain** [comment]
Moved to https://github.com/AtomLinter/linter-scss-lint/issues/88 and closing this issue to limit spam for those who got this working.

@willpracht let's move our discussion to #88 to figure this out.
