### ISSUE TITLE
Add Mike S as a maintainer

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-scss-lint#71]
This is an abandoned repo, Mike S (@SpainTrain) has shown some interest in maintaining this repo in our private google hangouts, I've been talking to him for the last few weeks and I trust him enough to say that he has my vote.
What do you think?
cc @AtomLinter/owners

**Comment by SpainTrain** [comment]
I would <3 it as my own

**Comment by Fequois** [comment]
As a user I would love to see a new maintainer. It hasn't worked very well for some time, so some lurv is most welcome.

**Comment by AsaAyers** [comment]
@SpainTrain Welcome to the team :)

**Comment by SpainTrain** [comment]
@AsaAyers thanks, but I don't think I am set as a collaborater.

**Comment by AsaAyers** [comment]
oops. I created a new team and added you to it, but forgot to add the repository to the team. I think it's fixed now.

**Comment by SpainTrain** [comment]
hehe, np, ty
