### ISSUE TITLE
No on-the-fly linting, only on save

### ISSUE THREAD

**Issue by ivancuric** [AtomLinter/linter-scss-lint#73]
While jshint has on the fly linting, and so does scss-lint on ST3, for some reason it doesn't work in Atom.

**Comment by steelbrain** [comment]
See https://github.com/AtomLinter/linter-scss-lint/pull/72

**Comment by bobrocke** [comment]
It's still not linting on-the-fly for me.

Atom 1.0.19
Mac OS X 10.10.5
scss-lint 2.0.0

**Comment by SpainTrain** [comment]
@bobrocke do you mind opening a new issue?  Also, could you open dev tools in atom (`cmd + shift + i` I believe) and see if there are any errors in the console?  Also, does it work *at all*?  That is, does it report issues properly on save?

**Comment by bobrocke** [comment]
I'll open a new issue. It does work on save. There are no errors in the console.
