### ISSUE TITLE
Refactor: Break up lint function

### ISSUE THREAD

**Issue by SpainTrain** [AtomLinter/linter-scss-lint#76]
Currently the `lint` method on `provider` is just one huge unreadable monolith.  It needs to be broken up to be readable and maintainable.  At minimum, the result parsing code should live in its own function.

Also, atom-linter helpers can probably be used to clean up further.

**Comment by SpainTrain** [comment]
@steelbrain do we have a label for cleanup or refactor?  I do not yet have collaborator priv.  Also assign to me =-D

**Comment by steelbrain** [comment]
Fixed by #72
