### ISSUE TITLE
rbenv: version `system' is not installed (set by RBENV_VERSION environment variable)

### ISSUE THREAD

**Issue by victorngkp** [AtomLinter/linter-scss-lint#78]
It doesn't lint anymore, and throws this error above whenever I save the `.scss` file.

**Comment by SpainTrain** [comment]
I think this has o do with your local ruby setup.

Can you try the advice here? https://github.com/sstephenson/rbenv/issues/693

**Comment by victorngkp** [comment]
Thanks!

**Comment by SpainTrain** [comment]
awesome, glad it worked
