### ISSUE TITLE
After update to El Capitan GM, linter throws error

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-scss-lint#79]
I've been using the beta of El Capitan without incident.  Last night I updated to the GM.

So far the only issue is that when I save a SCSS file, I now get an error every time:

`Failed to spawn command /usr/bin/scss-lint. Make sure /usr/bin/scss-lint is installed and on your PATH`

So, I go to terminal and type `which scss-lint` and get `/usr/local/bin/scss-lint`

My .bash_profile has, as always:
````
export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"
export NODE_PATH=/usr/local/lib/node_modules
````

Thoughts?

**Comment by steelbrain** [comment]
OSX doesn't pass `$PATH` to apps, start from cli as a workaround

**Comment by smlombardi** [comment]
Actually, I was looking at the bash path, I forgot to check the atom config. Further double-checking showed the atom config had `/usr/bin/scss-lint` (which was working before, but is wrong now).  I changed it to `/usr/local/bin/scss-lint` and now it works.
