### ISSUE TITLE
Custom config

### ISSUE THREAD

**Issue by Jursdotme** [AtomLinter/linter-scss-lint#8]
First of, great plugin.
But i cant seem to find a way to use custom config files.

We use a custom framework with a .yml file and i would like to use this with your plugin.

**Comment by curtisblackwell** [comment]
Any word on this? Setting up `.scss-lint.yml` breaks the plugin. Here's the warning from the debugger:

```
stderr /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/config.rb:156:in `dup': can't dup FalseClass (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/config.rb:156:in `ensure_exclude_paths_are_absolute'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/config.rb:148:in `block in ensure_linter_exclude_paths_are_absolute'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/config.rb:146:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/config.rb:146:in `ensure_linter_exclude_paths_are_absolute'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/config.rb:82:in `load_options_hash_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/config.rb:24:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/cli.rb:143:in `setup_configuration'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/lib/scss_lint/cli.rb:49:in `parse_arguments'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/bin/scss-lint:7:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/bin/scss-lint:6:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.30.0/bin/scss-lint:6:in `<top (required)>'
	from /usr/bin/scss-lint:23:in `load'
	from /usr/bin/scss-lint:23:in `<main>'
```

**Comment by adi-ads** [comment]
+1 any plan on this?

**Comment by martijnrusschen** [comment]
@curtisblackwell You're right. This works on per project. Thanks!

**Comment by leighkendell** [comment]
+1 for for the user directory, I'd like to have a global setting that I can then overwrite on a per project basis if needed.

**Comment by DeanAlexRainier** [comment]
The `findFile` function used for finding a `.scss-lint.yml` file works it's way up if it can't find it in the current working directory. My problem with this was that my config file in `~` was never found, because my project is residing in MAMP's htdocs folder. This folder is located under `/Applications/MAMP/htdocs`.

A quick fix was to move the `.scss-lint.yml` file to the `htdocs` folder.
But for me also a +1 to have it look in the user directory.

**Comment by leighkendell** [comment]
Cheers for that @DeanAlexRainier, I'm happy to chuck mine in the htdocs folder for now.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58
