### ISSUE TITLE
No linting

### ISSUE THREAD

**Issue by sevenfoxes** [AtomLinter/linter-scss-lint#80]
I've been digging through the issues and none of the proposed fixes work for me.

```bash
$ which scss-lint
/usr/local/bin/scss-lint

$ scss-lint -v
scss-lint 0.41.0

$ scss-lint application.css
application.css:796 [W] ColorVariable: Color literals like `#fbffcf` should only be used in variable declarations; they should be referred to via variable everywhere else.

$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

$ atom -v
1.0.11
```

```cson
linter: {}
"linter-scss-lint":
    executablePath: "/usr/local/bin/scss-lint"
```

linter-scss-lint returns "no issues" perpetually and no errors are ever reported. Any help is greatly appreciated.

**Comment by SpainTrain** [comment]
@sevenfoxes just published a new version of the plugin.  Could you update your plugin version and see if this issue persists? Thanks!

**Comment by sevenfoxes** [comment]
looks to be working! Thank you!

**Comment by SpainTrain** [comment]
Awesome!
