### ISSUE TITLE
Atom Ruby error

### ISSUE THREAD

**Issue by apexskier** [AtomLinter/linter-scss-lint#81]
I'm getting this error when atom runs the linter.

```
Error: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in to_specs': Could not find 'scss_lint' (>= 0) among 12 total gem(s) (Gem::LoadError) from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:into_spec' from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in gem' from /Users/cameronlittle/.gems/bin/scss-lint:22:in

'


Error: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'scss_lint' (>= 0) among 12 total gem(s) (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
    from /Users/cameronlittle/.gems/bin/scss-lint:22:in `<main>'
  at exit (/Users/cameronlittle/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:29:24)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)
```

I have the path configured properly in my config.cson.

The linter works fine from the command line.

scss-lint's version is `0.41.0`. OS X 10.10.5

**Comment by SpainTrain** [comment]
Could you describe how Ruby is configured on your machine?  Is ruby 2.0.0 the version that is used on the CLI?

**Comment by Dygerydoo** [comment]
Same issue, but I solved that running atom from terminal on my project path.

I used ```atom .``` and it worked.

**Comment by apexskier** [comment]
``` sh
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
```

I'm pretty sure ruby is installed with homebrew.

`atom .` does not work.

**Comment by AndrejGajdos** [comment]
I have the same issue.

```
$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```

Executable path is set to
```
/usr/local/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/bin/scss-lint
```

Linter works from command line.

**Comment by Arcanemagus** [comment]
@apexskier and @AndrejGajdos what do you get for `which scss-lint`?

**Comment by AndrejGajdos** [comment]
@Arcanemagus 

```
$ which scss-lint
/usr/local/bin/scss-lint
```

**Comment by Arcanemagus** [comment]
Can you get to the source of `/usr/local/bin/scss-lint` if it is a symlink or just open it if it isn't and see what ruby it is asking to be run under?

**Comment by AndrejGajdos** [comment]
@Arcanemagus it is executable file

```
kMDItemContentType = "public.unix-executable"
```

What do you mean *see what ruby it is asking to be run under*?

**Comment by Arcanemagus** [comment]
Ah, on Windows at least it is a wrapper script that calls `ruby` to execute the file so I figured it was the same case there. If you are getting the error at the start of this issue for some reason the version of `ruby` that Atom is finding doesn't know about the `scss-lint` gem you have installed.

You aren't by any chance using `rvm`, are you?

**Comment by AndrejGajdos** [comment]
@Arcanemagus I am sure I don't use `rvm`.

**Comment by Arcanemagus** [comment]
Can you verify `scss_lint` shows when you run `gem list` from a terminal, and if so close _all_ instances of Atom, then run `atom .` from the same terminal you ran `gem list` in, and see if this works?

**Comment by apexskier** [comment]
`which scss-lint` produces `~/.gems/bin/scss-lint` for me.

**Comment by Arcanemagus** [comment]
@apexskier same debugging steps outlined above:

Make sure `~/.gems/bin/scss-lint` isn't a wrapper script, and if it is make sure it is pointing to the right `ruby`.
Then try closing all Atom instances and from a terminal where `gem list` shows `scss_lint` run Atom (`atom .`) and see if this works.

**Comment by dpschen** [comment]
For me `gem install scss_lint` fixed the problem.
