### ISSUE TITLE
Error: env: ruby_executable_hooks: No such file or directory

### ISSUE THREAD

**Issue by vasudeva-chaynes** [AtomLinter/linter-scss-lint#83]
![scss-lint](https://cloud.githubusercontent.com/assets/10455341/9983686/803bb0dc-5fd4-11e5-8646-4f3e78a2e08d.png)

Installed as directed and scss-lint works from CLI, but get attached popup when saving .scss file in atom.

OS X, atom 1.0.15, ruby 2.2.3

**Comment by SpainTrain** [comment]
Have you tried https://github.com/AtomLinter/linter-scss-lint/issues/68#issuecomment-137231010 or https://github.com/AtomLinter/linter-scss-lint/issues/67#issuecomment-135485606 ?

**Comment by vasudeva-chaynes** [comment]
Using wrappers instead of bin in the path, as suggested by one of the comments in #68, solved my problem. Thanks!

**Comment by steelbrain** [comment]
Closing based on discussion above

**Comment by SpainTrain** [comment]
Great!  I may add this to the README since it's a somewhat common issue.

**Comment by vasudeva-chaynes** [comment]
Please do. I was thinking of suggesting that. It’s far from obvious.

**Comment by vasudeva-chaynes** [comment]
The best thing would be to fix whatever the issue is that makes this necessary. sass-lint works fine from CLI, so it seems there should be a way of making it work in atom.

**Comment by SpainTrain** [comment]
> best thing would be to fix whatever the issue is

agreed, but I am not super familiar with how those wrappers work (I actually don't know whether that is specific to nvm), so it would take quite a bit to track down.  Very happy to accept a PR to fix it though =-D
