### ISSUE TITLE
Hard time making this work on windows

### ISSUE THREAD

**Issue by labo-css** [AtomLinter/linter-scss-lint#85]
I can't figure out what i'm supposed to enter in the executable path. I put this :
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/scss_lint-0.41.0/lib/scss_lint
And it keep tell me scss lint is not found, i have installed the gem.

**Comment by labo-css** [comment]
Nevermind... i used the where command. It should be added in the docs.

**Comment by steelbrain** [comment]
@SpainTrain was going to add that to readme.

**Comment by SpainTrain** [comment]
PRs also welcome :blush:
