### ISSUE TITLE
Not linting on-the-fly

### ISSUE THREAD

**Issue by bobrocke** [AtomLinter/linter-scss-lint#86]
It's still not linting on-the-fly for me.

Atom 1.0.19
Mac OS X 10.10.5
scss-lint 2.0.0

It will lint on save. There are no errors in the console.

**Comment by Fequois** [comment]
8ce09eac92f4ae782ccce408b4caffff0aa4aaf6 kinda fixes this, but it's not packaged and released yet. You can always backport it! Not sure whether it works; last time I checked, it did not (on my system).

**Comment by steelbrain** [comment]
cc @SpainTrain

**Comment by SpainTrain** [comment]
@steelbrain can we release latest to apm?

**Comment by steelbrain** [comment]
@SpainTrain You are the captain of this ship sir :D

**Comment by Fequois** [comment]
If you drop it I'll confirm whether it works on my system either tonight or tomorrow as well. Can't remember what the problem was… come to think of it, I wonder if it wasn't a conflict between `scss_lint` and `psych`.

**Comment by SpainTrain** [comment]
> You are the captain of this ship

Don't you mean conductor of this train? ;-D

The latest package is now in the apm registry.  Apologies on the confusion.

**Comment by SpainTrain** [comment]
@Fequois It would be great if you could verify OTF linting now works for you.  Much thanks!

**Comment by Fequois** [comment]
@SpainTrain Working just fine. Just tried. :smile:

**Comment by steelbrain** [comment]
I guess this issue can be safely closed then
