### ISSUE TITLE
.scss-lint.yml doesn't work

### ISSUE THREAD

**Issue by ApfelUser** [AtomLinter/linter-scss-lint#87]
According to the **readme** linter-scss-lint does search for a `.scss-lint.yml` file:

 > Linter will start looking for `.scss-lint.yml` file in the same directory as the file that's being linted. If not found, it will move one level up the directory tree all the way up to the filesystem root.

My folder structure looks like this:

```
scss/
├─ main.scss
├─ includes/
│  ├─ somefile1.scss
│  └─ somefile2.scss 
└─ vendor
   ├─ bootstrap/
   │  └─ bootstrap specific scss
   │     └─ ....
   │        └─ ....
   └─ bootstrap.scss
```

My `.scss-lint.yml` file:

```yml
linters:
  ImportantRule:
    enabled: false
```
I am **e.g.** editing `somefile1.scss` at the moment. I moved the `.scss-lint.yml` file in

  * `/.scss-lint.yml`,
  * `/scss/.scss-lint.yml` and
  * `/scss/includes/.scss-lint.yml`

After moving I **always** completely restarted Atom. The `.scss-lint.yml` file doesn't get used in any of the 3 cases I tried. Am I doing something wrong? Or is this a bug? (My guess ^^)

**Comment by SpainTrain** [comment]
What is the result if you run on the CLI 

```bash
scss-lint <some scss file> --config=<path to .scss-lint.yml>
```

Also, what OS & version are you on?

**Comment by ApfelUser** [comment]
@SpainTrain I am so sorry. I just checked, I forgot to add the **dot** before the `scss-lint.yml`. My fault.

**Comment by SpainTrain** [comment]
No problem, glad we figured it out!
