### ISSUE TITLE
Linter can't find env: ruby_executable_hooks

### ISSUE THREAD

**Issue by SpainTrain** [AtomLinter/linter-scss-lint#88]
Issue from @willpracht moved from https://github.com/AtomLinter/linter-scss-lint/issues/68#issuecomment-144496261

```bash
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
/Users/willpracht/.rvm/rubies/ruby-2.2.1/bin/ruby
/Users/willpracht/.rvm/gems/ruby-2.2.1/bin/scss-lint
```

The error I get when changing my path to `wrappers`:

> Failed to spawn command `/Users/willpracht/.rvm/gems/ruby-2.2.1/wrappers/scss-lint`. Make sure `/Users/willpracht/.rvm/gems/ruby-2.2.1/wrappers/scss-lint` is installed and on your PATH

Followed by...

> Error: spawn /Users/willpracht/.rvm/gems/ruby-2.2.1/wrappers/scss-lint ENOENT

Seems like it's just that it can't find *scss-lint* via `wrappers`. Which, makes sense.

The other though... not sure what's going on there.

**Comment by SpainTrain** [comment]
`ENOENT` means it cannot find the file at all.  Can you

```bash
stat /Users/willpracht/.rvm/gems/ruby-2.2.1/wrappers/scss-lint
ls -al /Users/willpracht/.rvm/gems/ruby-2.2.1/wrappers/
```

**Comment by SpainTrain** [comment]
Sorry, not super familiar with wrappers so just suggesting general troubleshooting - have you already tried reinstalling the gem?

**Comment by willpracht** [comment]
Thanks for looking into this :).

Yeah, so switching it back to the regular `bin` path gets me back to that original error: 

>  Error: env: ruby_executable_hooks: No such file or directory

I've updated the *scss-lint* gem, but still get the same error.

This *used* to work, but for the last few versions of *linter-scss-lint* it's been throwing this error.

I'm wondering if it has something to do with rvm. I want to say it maybe started after I went to that over the built-in Ruby instance from MacOS.

**Comment by willpracht** [comment]
So... some combination of reinstalling the *scss_lint* gem once again and updating the *atom-linter* plugin to `1.7.2` has seemingly fixed everything for me!

Thanks for all the help with this. It's much appreciated. Happy linting :).

**Comment by SpainTrain** [comment]
hahahah, glad the gremlins got worked out!

![](https://videovortex.files.wordpress.com/2014/09/gremlins_inside.jpg)

**Comment by steelbrain** [comment]
@SpainTrain that image is kinda scary to be honest

**Comment by SpainTrain** [comment]
:fearful: Updated the image to be less terrifying (and more adorable) for those unfamiliar with the '84 comedy-horror film, but still reference it for those who are :smile_cat:

**Comment by steelbrain** [comment]
:heart:
