### ISSUE TITLE
Only the First Error is Shown

### ISSUE THREAD

**Issue by ChrisBaker97** [AtomLinter/linter-scss-lint#9]
I'm having a strange issue where linter-scss-lint has no problem highlighting multiple warnings, but if even a single error is detected, the indication for the warnings and all subsequent errors disappears. I've isolated this to linter-scss-lint, as it doesn't occur with other linter plug-ins, such as linter-ruby.

![linter-scss-cap](https://cloud.githubusercontent.com/assets/2942518/4453354/00a63c94-485a-11e4-84ec-f0e08bbba150.gif)

No errors in the console, as you can see.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58
