### ISSUE TITLE
scss_lint not found

### ISSUE THREAD

**Issue by akhyarrh** [AtomLinter/linter-scss-lint#90]
```
Error: /home/akhyarrh/.rubies/ruby-2.1.7/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'scss_lint' (>= 0) among 8 total gem(s) (Gem::LoadError)
    from /home/akhyarrh/.rubies/ruby-2.1.7/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
    from /home/akhyarrh/.rubies/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
    from /home/akhyarrh/.gem/ruby/2.1.7/bin/scss-lint:22:in `<main>'
  at exit (/home/akhyarrh/.atom/packages/linter-htmlhint/node_modules/atom-linter/lib/helpers.coffee:32:24)
  at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /opt/atom/resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)
```

Using `chruby`, Mint rafaela. I've 'enjoying' this problem for month :|

Any idea to fix this ?

**Comment by SpainTrain** [comment]
Strange, does it work when you run it on the CLI?

**Comment by akhyarrh** [comment]
Perfect when on CLI
![screenshot_2015-10-03_01-04-03](https://cloud.githubusercontent.com/assets/10618799/10252537/ae400966-696a-11e5-96fc-1d41036af24f.png)

**Comment by SpainTrain** [comment]
Can you try running atom from the CLI and see if this issue persists?

**Comment by akhyarrh** [comment]
This issue gone if running Atom from CLI. Seems like a problem with `chruby` ?. `linter-rubocop` throw similiar error

**Comment by SpainTrain** [comment]
> This issue gone if running Atom from CLI. Seems like a problem with chruby ?. linter-rubocop throw similiar error

Glad we found a workaround for you.

I think it is generally just an issue with the ENV atom runs with when run from CLI vs. run from launcher.  I thought I saw a ticket in core related to fixing this, but not sure I can find it.  @steelbrain do you know if such a ticket existed or exists?

**Comment by steelbrain** [comment]
@SpainTrain Yep! This is an env issue. It was fixed for windows, always worked on linux and worked around on mac. It was worked around by people by running atom from terminal or by creating `shadow` executables like
```sh
#!/bin/bash
source ~/.shell_customizations
/usr/local/bin/robocup $@
```
or by specifying env from `~/.atom/init.coffee`. There's **nothing** really broken about this, it's not just about Atom, **any** Mac app that isn't run from the terminal doesn't get correct ENV vars.
